"""empty message

Revision ID: 22cf196011e4
Revises: 463ea6390bda
Create Date: 2022-10-20 22:45:09.384359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cf196011e4'
down_revision = '463ea6390bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('videos', 'description',
    #            existing_type=sa.VARCHAR(length=200),
    #            type_=sa.Text(),
    #            existing_nullable=True)
    op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'])
    op.drop_column('videos', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('link', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    # op.alter_column('videos', 'description',
    #            existing_type=sa.Text(),
    #            type_=sa.VARCHAR(length=200),
    #            existing_nullable=True)
    # ### end Alembic commands ###
