"""empty message

Revision ID: 27336df4bbf3
Revises: 480b8e2fe409
Create Date: 2022-10-28 21:01:17.345182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27336df4bbf3'
down_revision = '480b8e2fe409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('codeSnippets')
    op.drop_index('ix_token_block_list_jti', table_name='token_block_list')
    op.drop_table('token_block_list')
    op.drop_table('projectIdeas')
    op.drop_table('test')
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('articles', 'added_on')
    op.add_column('gifs', sa.Column('local_path', sa.String(length=64), nullable=True))
    op.add_column('gifs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('gifs', 'title')
    op.drop_column('gifs', 'timestamp')
    op.drop_column('gifs', 'link')
    op.drop_column('gifs', 'author')
    op.drop_column('gifs', 'description')
    op.drop_column('gifs', 'path')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'email')
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('videos', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_column('videos', 'timestamp')
    op.drop_column('videos', 'length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('length', sa.INTEGER(), nullable=True))
    op.add_column('videos', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.alter_column('videos', 'description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('videos', 'created_at')
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.add_column('gifs', sa.Column('path', sa.VARCHAR(length=64), nullable=True))
    op.add_column('gifs', sa.Column('description', sa.VARCHAR(length=200), nullable=True))
    op.add_column('gifs', sa.Column('author', sa.VARCHAR(length=64), nullable=True))
    op.add_column('gifs', sa.Column('link', sa.VARCHAR(length=64), nullable=True))
    op.add_column('gifs', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('gifs', sa.Column('title', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('gifs', 'created_at')
    op.drop_column('gifs', 'local_path')
    op.add_column('articles', sa.Column('added_on', sa.DATETIME(), nullable=True))
    op.drop_column('articles', 'created_at')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('string1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('num1', sa.INTEGER(), nullable=True),
    sa.Column('string2', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectIdeas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('token_block_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_block_list_jti', 'token_block_list', ['jti'], unique=False)
    op.create_table('codeSnippets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('project_ideas')
    op.drop_table('code_snippets')
    # ### end Alembic commands ###
