"""empty message

Revision ID: 56ce49652ec6
Revises: 50105b1b1b5d
Create Date: 2022-10-29 23:43:32.978257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ce49652ec6'
down_revision = '50105b1b1b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_block_list_jti'), 'token_block_list', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_block_list_jti'), table_name='token_block_list')
    op.drop_table('token_block_list')
    # ### end Alembic commands ###
