"""empty message

Revision ID: 9b0aae5157d6
Revises: 338e8601138d
Create Date: 2022-10-04 00:35:07.291055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0aae5157d6'
down_revision = '338e8601138d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url', sa.String(length=64), nullable=True))
    op.add_column('videos', sa.Column('youtube_id', sa.String(length=64), nullable=True))
    op.add_column('videos', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'])
    op.drop_column('videos', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('link', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'user')
    op.drop_column('videos', 'youtube_id')
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###
