"""empty message

Revision ID: aa1aee1027b6
Revises: f11d21db584d
Create Date: 2022-10-20 22:42:32.020886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1aee1027b6'
down_revision = 'f11d21db584d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('videos', 'description',
    #            existing_type=sa.VARCHAR(length=200),
    #            type_=sa.Text(),
    #            existing_nullable=True)
    op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'])
    op.drop_column('videos', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('link', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    # op.alter_column('videos', 'description',
    #            existing_type=sa.Text(),
    #            type_=sa.VARCHAR(length=200),
    #            existing_nullable=True)
    # ### end Alembic commands ###
