"""empty message

Revision ID: e0853b3c54f6
Revises: 27336df4bbf3
Create Date: 2022-10-28 22:10:37.883098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0853b3c54f6'
down_revision = '27336df4bbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gifs_name_key', 'gifs', type_='unique')
    op.add_column('videos', sa.Column('length', sa.Integer(), nullable=True))
    op.drop_constraint('videos_name_key', 'videos', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('videos_name_key', 'videos', ['name'])
    op.drop_column('videos', 'length')
    op.create_unique_constraint('gifs_name_key', 'gifs', ['name'])
    # ### end Alembic commands ###
