"""empty message

Revision ID: f11d21db584d
Revises: 9b0aae5157d6
Create Date: 2022-10-20 22:40:53.414889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11d21db584d'
down_revision = '9b0aae5157d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_block_list_jti'), 'token_block_list', ['jti'], unique=False)
    # op.alter_column('videos', 'description',
    #            existing_type=sa.VARCHAR(length=200),
    #            type_=sa.Text(),
    #            existing_nullable=True)
    op.create_foreign_key(None, 'videos', 'users', ['user'], ['id'])
    op.drop_column('videos', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('link', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    # op.alter_column('videos', 'description',
    #            existing_type=sa.Text(),
    #            type_=sa.VARCHAR(length=200),
    #            existing_nullable=True)
    op.drop_index(op.f('ix_token_block_list_jti'), table_name='token_block_list')
    op.drop_table('token_block_list')
    # ### end Alembic commands ###
